version: "3.5"

services:
  php:
    build:
      context: php
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./app:/var/www/html

  mariadb:
    image: mariadb:10.5.5
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
    - ./databases/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - 127.0.0.1:8080:8080
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD:
